# Generated by Django 5.0.1 on 2024-01-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kalendarz', '0004_alter_calendar_doctor_alter_reservation_data'),
        ('patient', '0001_initial'),
        ('worker', '0004_doctor_is_worker_secretary_is_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='scheduled', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('reservation_copy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kalendarz.reservation')),
            ],
        ),
    ]
